<?xml version="1.0"?>
<robot name="ws_box" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- utils /-->
  <xacro:include filename="$(find lwr_description)/model/utils.xacro"/>	

  <!-- properties /-->
  <xacro:property name="length" value="2"/>
  <xacro:property name="width" value="1"/>
  <xacro:property name="height" value="1"/>
  <xacro:property name="y0" value="0.85"/>

  <!-- URDF model /-->
  <xacro:macro name="ws_box">

    <!-- Workspace box -->
    <link name="ws_box">
      <collision>
	<origin xyz="0 ${y0} ${height/2}" rpy="0 0 0"/>
	<geometry>
	  <box size="${length} ${width} ${height}"/>
	</geometry>
      </collision>
      
      <visual>
	<origin xyz="0 ${y0} ${height/2}" rpy="0 0 0"/>
	<geometry>
          <box size="${length} ${width} ${height}"/>
	</geometry>
      </visual>
      
      <inertial>
	<origin xyz="0 ${y0} ${height/2}" rpy="0 0 0"/>
	<mass value="10000"/>
	<cuboid_inertia_def length="${length}" width="${width}" height="${height}" mass="1000"/>
      </inertial>
    </link>

  </xacro:macro>

  <link name="world" />
  
  <joint name="ws_joint"  type="fixed">
    <parent link="world"/>
    <child link="ws_box"/>
  </joint>

  <!-- using the models -->
  <xacro:ws_box/>
  
</robot>
